# Autonomous Drone Delivery & Routing System

In [15]:
import sys
!{sys.executable} -m pip install osmnx

Collecting osmnx
  Using cached osmnx-2.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting geopandas>=1.0.1 (from osmnx)
  Using cached geopandas-1.1.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: networkx>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from osmnx) (3.5)
Requirement already satisfied: numpy>=1.24 in c:\users\dell\anaconda3\lib\site-packages (from osmnx) (2.3.5)
Requirement already satisfied: pandas>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from osmnx) (2.3.3)
Requirement already satisfied: requests>=2.30 in c:\users\dell\anaconda3\lib\site-packages (from osmnx) (2.32.5)
Collecting shapely>=2.0 (from osmnx)
  Downloading shapely-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.1 kB)
Collecting pyogrio>=0.7.2 (from geopandas>=1.0.1->osmnx)
  Downloading pyogrio-0.12.1-cp313-cp313-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in c:\users\dell\anaconda3\lib\site-packages (from geopandas>=1.0.1->osmnx) (25.0)
Collecting pyproj>=3.5.0 (from geopandas>=1.0.1->osmnx)
  Downloading pyproj-3.7.2-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.5->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: certifi in c:\users\dell\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas>=1.0.1->osmnx) (2026.1.4)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->osmnx) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.30->osmnx) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.30->osmnx) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.30->osmnx) (2.5.0)
Using cached osmnx-2.1.0-py3-none-any.whl (104 kB)
Using cached geopandas-1.1.3-py3-none-any.whl (342 kB)
Downloading pyogrio-0.12.1-cp313-cp313-win_amd64.whl (22.9 MB)
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/22.9 MB ? eta -:--:--
    --------------------------------------- 0.5/22.9 MB 875.8 kB/s eta 0:00:26
    --------------------------------------- 0.5/22.9 MB 875.8 kB/s eta 0:00:26
   - -------------------------------------- 0.8/22.9 MB 924.0 kB/s eta 0:00:24
   - -------------------------------------- 1.0/22.9 MB 1.0 MB/s eta 0:00:22
   -- ------------------------------------- 1.3/22.9 MB 1.1 MB/s eta 0:00:21
   -- ------------------------------------- 1.6/22.9 MB 1.1 MB/s eta 0:00:20
   --- ------------------------------------ 1.8/22.9 MB 1.1 MB/s eta 0:00:19
   --- ------------------------------------ 2.1/22.9 MB 1.1 MB/s eta 0:00:19
   ---- ----------------------------------- 2.4/22.9 MB 1.1 MB/s eta 0:00:20
   ---- ----------------------------------- 2.4/22.9 MB 1.1 MB/s eta 0:00:20
   ---- ----------------------------------- 2.4/22.9 MB 1.1 MB/s eta 0:00:20
   ---- ----------------------------------- 2.4/22.9 MB 1.1 MB/s eta 0:00:20
   ---- ----------------------------------- 2.6/22.9 MB 854.3 kB/s eta 0:00:24
   ---- ----------------------------------- 2.6/22.9 MB 854.3 kB/s eta 0:00:24
   ---- ----------------------------------- 2.6/22.9 MB 854.3 kB/s eta 0:00:24
   ---- ----------------------------------- 2.6/22.9 MB 854.3 kB/s eta 0:00:24
   ---- ----------------------------------- 2.6/22.9 MB 854.3 kB/s eta 0:00:24
   ----- ---------------------------------- 2.9/22.9 MB 688.9 kB/s eta 0:00:30
   ----- ---------------------------------- 2.9/22.9 MB 688.9 kB/s eta 0:00:30
   ----- ---------------------------------- 2.9/22.9 MB 688.9 kB/s eta 0:00:30
   ----- ---------------------------------- 3.1/22.9 MB 647.3 kB/s eta 0:00:31
   ----- ---------------------------------- 3.1/22.9 MB 647.3 kB/s eta 0:00:31
   ----- ---------------------------------- 3.1/22.9 MB 647.3 kB/s eta 0:00:31
   ----- ---------------------------------- 3.1/22.9 MB 647.3 kB/s eta 0:00:31
   ----- ---------------------------------- 3.4/22.9 MB 607.4 kB/s eta 0:00:33
   ------ --------------------------------- 3.7/22.9 MB 609.9 kB/s eta 0:00:32
   ------ --------------------------------- 3.7/22.9 MB 609.9 kB/s eta 0:00:32
   ------ --------------------------------- 3.7/22.9 MB 609.9 kB/s eta 0:00:32
   ------ --------------------------------- 3.7/22.9 MB 609.9 kB/s eta 0:00:32
   ------ --------------------------------- 3.9/22.9 MB 586.2 kB/s eta 0:00:33
   ------- -------------------------------- 4.2/22.9 MB 598.4 kB/s eta 0:00:32
   ------- -------------------------------- 4.2/22.9 MB 598.4 kB/s eta 0:00:32
   ------- -------------------------------- 4.5/22.9 MB 606.8 kB/s eta 0:00:31
   ------- -------------------------------- 4.5/22.9 MB 606.8 kB/s eta 0:00:31
   -------- ------------------------------- 4.7/22.9 MB 600.7 kB/s eta 0:00:31
   -------- ------------------------------- 4.7/22.9 MB 600.7 kB/s eta 0:00:31
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   -------- ------------------------------- 5.0/22.9 MB 602.0 kB/s eta 0:00:30
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.2/22.9 MB 535.1 kB/s eta 0:00:34
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   --------- ------------------------------ 5.5/22.9 MB 457.4 kB/s eta 0:00:39
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 5.8/22.9 MB 413.2 kB/s eta 0:00:42
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.0/22.9 MB 353.2 kB/s eta 0:00:48
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ---------- ----------------------------- 6.3/22.9 MB 329.0 kB/s eta 0:00:51
   ----------- ---------------------------- 6.6/22.9 MB 270.0 kB/s eta 0:01:01
   ----------- ---------------------------- 6.6/22.9 MB 270.0 kB/s eta 0:01:01
   ----------- ---------------------------- 6.6/22.9 MB 270.0 kB/s eta 0:01:01
   ----------- ---------------------------- 6.8/22.9 MB 274.0 kB/s eta 0:00:59
   ----------- ---------------------------- 6.8/22.9 MB 274.0 kB/s eta 0:00:59
   ----------- ---------------------------- 6.8/22.9 MB 274.0 kB/s eta 0:00:59
   ------------ --------------------------- 7.1/22.9 MB 277.4 kB/s eta 0:00:58
   ------------ --------------------------- 7.1/22.9 MB 277.4 kB/s eta 0:00:58
   ------------ --------------------------- 7.1/22.9 MB 277.4 kB/s eta 0:00:58
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------ --------------------------- 7.3/22.9 MB 280.3 kB/s eta 0:00:56
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.6/22.9 MB 261.3 kB/s eta 0:00:59
   ------------- -------------------------- 7.9/22.9 MB 45.8 kB/s eta 0:05:30
   ------------- -------------------------- 7.9/22.9 MB 45.8 kB/s eta 0:05:30

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (8.7 MB/22.9 MB, attempt 1)

## Purpose:
- Explore datasets
- Understand columns
- Verify formats

In [16]:
# load mdrp

import pandas as pd

df = pd.read_csv(
    "../datasets/mdrp/MDRP-P-n16-k8.csv"
)

df.head()

   NODE_ID      TYPE     X     Y  DEMAND  SERVICE_TIME
0        0     DEPOT  30.0  40.0    0.00          0.00
1        1  CUSTOMER  37.0  52.0    0.20          2.49
2        2  CUSTOMER  49.0  49.0    0.64          2.30
3        3  CUSTOMER  52.0  64.0    0.46          2.70
4        4  CUSTOMER  31.0  62.0    0.11          2.32

In [ ]:
# load osm

# import osmnx as ox

# north, south, east, west = 22.45, 22.20, 91.95, 91.70

# graph = ox.graph_from_bbox(
#     (north, south, east, west),
#     network_type="drive"
# )

# graph

ConnectionError: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016D381E3ED0>: Failed to resolve 'overpass-api.de' ([Errno 11001] getaddrinfo failed)"))

In [21]:
# Generate requests

import pandas as pd

requests = pd.read_csv(
    "../datasets/synthetic/requests.csv"
)

requests.head()

   request_id   source destination priority
0           1  Depot_A  Customer_1     High
1           2  Depot_A  Customer_2   Medium
2           3  Depot_A  Customer_3      Low