# Autonomous Drone Delivery & Routing System

## Purpose:
- Explore datasets
- Understand columns
- Verify formats

In [16]:
# load mdrp

import pandas as pd

df = pd.read_csv(
    "../datasets/mdrp/MDRP-P-n16-k8.csv"
)

df.head()

   NODE_ID      TYPE     X     Y  DEMAND  SERVICE_TIME
0        0     DEPOT  30.0  40.0    0.00          0.00
1        1  CUSTOMER  37.0  52.0    0.20          2.49
2        2  CUSTOMER  49.0  49.0    0.64          2.30
3        3  CUSTOMER  52.0  64.0    0.46          2.70
4        4  CUSTOMER  31.0  62.0    0.11          2.32

In [ ]:
# load osm

# import osmnx as ox

# north, south, east, west = 22.45, 22.20, 91.95, 91.70

# graph = ox.graph_from_bbox(
#     (north, south, east, west),
#     network_type="drive"
# )

# graph

ConnectionError: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016D381E3ED0>: Failed to resolve 'overpass-api.de' ([Errno 11001] getaddrinfo failed)"))

In [21]:
# Generate requests

import pandas as pd

requests = pd.read_csv(
    "../datasets/synthetic/requests.csv"
)

requests.head()

   request_id   source destination priority
0           1  Depot_A  Customer_1     High
1           2  Depot_A  Customer_2   Medium
2           3  Depot_A  Customer_3      Low